os: osx

install:
  - export PATH=$PATH:/home/travis/.phpenv/bin
  - eval "$(phpenv init -)"
  - phpenv global 7.1
  - composer self-update
  - composer install -o --no-interaction --prefer-dist
  - ./init.sh

script:
  - vendor/bin/codecept run -vvv

cache:
  directories: $HOME/.composer/cache
