os: osx

language: php

install:
  - composer self-update
  - composer install -o --no-interaction --prefer-dist
  - ./init.sh

script:
  - vendor/bin/codecept run -vvv

cache:
  directories: $HOME/.composer/cache
